#!/usr/bin/env python3
"""Create reproducible train, validation and test dataset partitions.

Positive response classes are allocated independently so that rare positive
subclasses remain represented in validation and test whenever possible.
Negative examples are partitioned using the same target fractions.

The test set remains isolated from model development and hyperparameter tuning.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd


DEFAULT_RANDOM_SEED = 123
DEFAULT_TRAIN_FRACTION = 0.70
DEFAULT_VALIDATION_FRACTION = 0.15
DEFAULT_TEST_FRACTION = 0.15


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Create reproducible train/validation/test partitions."
    )

    parser.add_argument(
        "--dataset",
        type=Path,
        default=Path("data/processed/master_dataset.csv"),
        help="Master dataset generated by 01_build_dataset.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/splits"),
        help="Directory where split files will be written.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=Path("data/metadata/split_summary.json"),
        help="JSON file containing partition metadata.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_RANDOM_SEED,
        help="Random seed used to reproduce the partitions.",
    )
    parser.add_argument(
        "--train-fraction",
        type=float,
        default=DEFAULT_TRAIN_FRACTION,
        help="Fraction assigned to training.",
    )
    parser.add_argument(
        "--validation-fraction",
        type=float,
        default=DEFAULT_VALIDATION_FRACTION,
        help="Fraction assigned to validation.",
    )
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=DEFAULT_TEST_FRACTION,
        help="Fraction assigned to testing.",
    )

    return parser.parse_args()


def validate_fractions(
    train_fraction: float,
    validation_fraction: float,
    test_fraction: float,
) -> None:
    """Validate partition fractions."""

    fractions = [train_fraction, validation_fraction, test_fraction]

    if any(fraction <= 0 or fraction >= 1 for fraction in fractions):
        raise ValueError(
            "All partition fractions must be greater than 0 and less than 1."
        )

    total = sum(fractions)

    if abs(total - 1.0) > 1e-9:
        raise ValueError(
            "Train, validation and test fractions must sum to 1. "
            f"Observed sum: {total}"
        )


def load_dataset(path: Path) -> pd.DataFrame:
    """Load and validate the master dataset."""

    if not path.exists():
        raise FileNotFoundError(f"Master dataset not found: {path}")

    dataframe = pd.read_csv(path)

    required_columns = {
        "sample_id",
        "sequence_id",
        "sequence",
        "label",
        "response_class",
        "sequence_hash",
        "gc_content",
    }

    missing_columns = required_columns - set(dataframe.columns)

    if missing_columns:
        raise ValueError(
            "Master dataset is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    if dataframe["sample_id"].duplicated().any():
        raise ValueError("Duplicated sample IDs detected in master dataset.")

    if dataframe["sequence_hash"].duplicated().any():
        raise ValueError("Duplicated sequence hashes detected in master dataset.")

    observed_labels = set(dataframe["label"].unique())

    if observed_labels != {0, 1}:
        raise ValueError(
            "Expected binary labels {0, 1}. "
            f"Observed labels: {sorted(observed_labels)}"
        )

    positive_mask = dataframe["label"] == 1

    if dataframe.loc[positive_mask, "response_class"].isna().any():
        raise ValueError(
            "Positive samples without response_class metadata were detected."
        )

    return dataframe


def allocate_counts(
    n_samples: int,
    train_fraction: float,
    validation_fraction: float,
    test_fraction: float,
) -> tuple[int, int, int]:
    """Allocate integer split sizes while preserving all samples.

    For groups with at least three samples, validation and test each receive
    at least one example. This is important for rare positive subclasses.
    """

    if n_samples < 3:
        raise ValueError(
            "Each independently partitioned group must contain at least "
            f"3 samples. Observed: {n_samples}"
        )

    validation_count = max(1, int(round(n_samples * validation_fraction)))
    test_count = max(1, int(round(n_samples * test_fraction)))
    train_count = n_samples - validation_count - test_count

    if train_count < 1:
        raise ValueError(
            "The requested fractions leave no training samples for a group "
            f"of size {n_samples}."
        )

    return train_count, validation_count, test_count


def partition_group(
    dataframe: pd.DataFrame,
    rng: np.random.Generator,
    train_fraction: float,
    validation_fraction: float,
    test_fraction: float,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Randomly partition one homogeneous group."""

    train_count, validation_count, test_count = allocate_counts(
        len(dataframe),
        train_fraction,
        validation_fraction,
        test_fraction,
    )

    shuffled_indices = rng.permutation(dataframe.index.to_numpy())

    train_end = train_count
    validation_end = train_count + validation_count

    train_indices = shuffled_indices[:train_end]
    validation_indices = shuffled_indices[train_end:validation_end]
    test_indices = shuffled_indices[validation_end:]

    if len(test_indices) != test_count:
        raise RuntimeError("Internal split-size mismatch.")

    return (
        dataframe.loc[train_indices].copy(),
        dataframe.loc[validation_indices].copy(),
        dataframe.loc[test_indices].copy(),
    )


def dataframe_checksum(dataframe: pd.DataFrame) -> str:
    """Generate a stable checksum from ordered sample IDs."""

    content = "\n".join(dataframe["sample_id"].astype(str))
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def split_counts(dataframe: pd.DataFrame) -> dict:
    """Summarize class and response-class counts for one partition."""

    positive_classes = (
        dataframe.loc[dataframe["label"] == 1, "response_class"]
        .value_counts()
        .sort_index()
    )

    return {
        "total": int(len(dataframe)),
        "negative": int((dataframe["label"] == 0).sum()),
        "positive": int((dataframe["label"] == 1).sum()),
        "positive_response_classes": {
            str(class_name): int(count)
            for class_name, count in positive_classes.items()
        },
        "mean_gc": float(dataframe["gc_content"].mean()),
        "positive_mean_gc": float(
            dataframe.loc[dataframe["label"] == 1, "gc_content"].mean()
        ),
        "negative_mean_gc": float(
            dataframe.loc[dataframe["label"] == 0, "gc_content"].mean()
        ),
        "checksum": dataframe_checksum(dataframe),
    }


def validate_partitions(
    full_dataset: pd.DataFrame,
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> None:
    """Validate independence and completeness of dataset partitions."""

    train_ids = set(train_df["sample_id"])
    validation_ids = set(validation_df["sample_id"])
    test_ids = set(test_df["sample_id"])

    if train_ids & validation_ids:
        raise ValueError("Train and validation partitions overlap.")

    if train_ids & test_ids:
        raise ValueError("Train and test partitions overlap.")

    if validation_ids & test_ids:
        raise ValueError("Validation and test partitions overlap.")

    combined_ids = train_ids | validation_ids | test_ids
    expected_ids = set(full_dataset["sample_id"])

    if combined_ids != expected_ids:
        missing = expected_ids - combined_ids
        unexpected = combined_ids - expected_ids

        raise ValueError(
            "Partition IDs do not reconstruct the complete dataset. "
            f"Missing={len(missing)}, unexpected={len(unexpected)}"
        )

    combined = pd.concat(
        [
            train_df.assign(split_name="train"),
            validation_df.assign(split_name="validation"),
            test_df.assign(split_name="test"),
        ],
        ignore_index=True,
    )

    if combined["sequence_hash"].duplicated().any():
        raise ValueError(
            "An exact sequence appears in more than one partition."
        )

    for name, partition in [
        ("train", train_df),
        ("validation", validation_df),
        ("test", test_df),
    ]:
        labels = set(partition["label"].unique())

        if labels != {0, 1}:
            raise ValueError(
                f"{name} partition does not contain both binary classes."
            )

        positive_classes = set(
            partition.loc[
                partition["label"] == 1,
                "response_class",
            ].dropna()
        )

        expected_positive_classes = set(
            full_dataset.loc[
                full_dataset["label"] == 1,
                "response_class",
            ].dropna()
        )

        if positive_classes != expected_positive_classes:
            raise ValueError(
                f"{name} partition does not contain every positive subclass. "
                f"Observed={sorted(positive_classes)}, "
                f"expected={sorted(expected_positive_classes)}"
            )


def main() -> int:
    """Create and save reproducible dataset partitions."""

    args = parse_args()

    try:
        validate_fractions(
            args.train_fraction,
            args.validation_fraction,
            args.test_fraction,
        )

        dataframe = load_dataset(args.dataset).copy()
        rng = np.random.default_rng(args.seed)

        train_parts: list[pd.DataFrame] = []
        validation_parts: list[pd.DataFrame] = []
        test_parts: list[pd.DataFrame] = []

        negative_df = dataframe.loc[dataframe["label"] == 0].copy()

        negative_train, negative_validation, negative_test = partition_group(
            negative_df,
            rng,
            args.train_fraction,
            args.validation_fraction,
            args.test_fraction,
        )

        train_parts.append(negative_train)
        validation_parts.append(negative_validation)
        test_parts.append(negative_test)

        positive_df = dataframe.loc[dataframe["label"] == 1].copy()

        for response_class in sorted(
            positive_df["response_class"].dropna().unique()
        ):
            class_df = positive_df.loc[
                positive_df["response_class"] == response_class
            ].copy()

            class_train, class_validation, class_test = partition_group(
                class_df,
                rng,
                args.train_fraction,
                args.validation_fraction,
                args.test_fraction,
            )

            train_parts.append(class_train)
            validation_parts.append(class_validation)
            test_parts.append(class_test)

        train_df = pd.concat(train_parts, ignore_index=True)
        validation_df = pd.concat(validation_parts, ignore_index=True)
        test_df = pd.concat(test_parts, ignore_index=True)

        # Reproducibly shuffle each completed partition.
        train_df = train_df.sample(
            frac=1,
            random_state=args.seed,
        ).reset_index(drop=True)

        validation_df = validation_df.sample(
            frac=1,
            random_state=args.seed + 1,
        ).reset_index(drop=True)

        test_df = test_df.sample(
            frac=1,
            random_state=args.seed + 2,
        ).reset_index(drop=True)

        train_df["split"] = "train"
        validation_df["split"] = "validation"
        test_df["split"] = "test"

        validate_partitions(
            dataframe,
            train_df,
            validation_df,
            test_df,
        )

        args.output_dir.mkdir(parents=True, exist_ok=True)
        args.summary.parent.mkdir(parents=True, exist_ok=True)

        train_df.to_csv(args.output_dir / "train.csv", index=False)
        validation_df.to_csv(
            args.output_dir / "validation.csv",
            index=False,
        )
        test_df.to_csv(args.output_dir / "test.csv", index=False)

        manifest_columns = [
            "sample_id",
            "sequence_id",
            "label",
            "response_class",
            "sequence_hash",
            "split",
        ]

        train_df[manifest_columns].to_csv(
            args.output_dir / "train_manifest.csv",
            index=False,
        )
        validation_df[manifest_columns].to_csv(
            args.output_dir / "validation_manifest.csv",
            index=False,
        )
        test_df[manifest_columns].to_csv(
            args.output_dir / "test_manifest.csv",
            index=False,
        )

        summary = {
            "source_dataset": str(args.dataset),
            "random_seed": args.seed,
            "fractions_requested": {
                "train": args.train_fraction,
                "validation": args.validation_fraction,
                "test": args.test_fraction,
            },
            "partition_strategy": (
                "independent_allocation_by_binary_negative_class_and_"
                "positive_response_subclass"
            ),
            "rare_class_policy": (
                "groups_with_at_least_three_samples receive at least one "
                "validation and one test example"
            ),
            "test_set_policy": (
                "isolated_until_final_model_evaluation"
            ),
            "full_dataset": split_counts(dataframe),
            "train": split_counts(train_df),
            "validation": split_counts(validation_df),
            "test": split_counts(test_df),
            "actual_fractions": {
                "train": float(len(train_df) / len(dataframe)),
                "validation": float(
                    len(validation_df) / len(dataframe)
                ),
                "test": float(len(test_df) / len(dataframe)),
            },
            "overlap_checks": {
                "train_validation_sample_overlap": 0,
                "train_test_sample_overlap": 0,
                "validation_test_sample_overlap": 0,
                "exact_sequence_overlap_across_partitions": 0,
            },
        }

        with args.summary.open("w", encoding="utf-8") as handle:
            json.dump(
                summary,
                handle,
                indent=2,
                ensure_ascii=False,
            )

        print("=" * 72)
        print("DATASET SPLITS CREATED SUCCESSFULLY")
        print("=" * 72)

        for name, partition in [
            ("Train", train_df),
            ("Validation", validation_df),
            ("Test", test_df),
        ]:
            positive_count = int((partition["label"] == 1).sum())
            negative_count = int((partition["label"] == 0).sum())

            class_counts = (
                partition.loc[
                    partition["label"] == 1,
                    "response_class",
                ]
                .value_counts()
                .sort_index()
                .to_dict()
            )

            print(
                f"{name:12s}: "
                f"total={len(partition):4d}, "
                f"positive={positive_count:3d}, "
                f"negative={negative_count:4d}, "
                f"positive_classes={class_counts}"
            )

        print(f"Random seed: {args.seed}")
        print(f"Summary:     {args.summary}")
        print("=" * 72)

    except (
        FileNotFoundError,
        ValueError,
        RuntimeError,
        pd.errors.ParserError,
    ) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
